site_name: 中圣荷西基督徒会堂 - 2022退休會
site_url: https://ccic-csj.github.io/retreat2022/
theme:
  logo: images/favicon.png
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - def_list
  - def_list
  - pymdownx.superfences
  - cell_row_span
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - glightbox
  - search:
      lang:
        - en
extra_css:
#  - stylesheets/extra.css
  - stylesheets/style.css
extra:
  generator: false
