site_name: 中圣荷西基督徒会堂 - 退休會 2022
theme:
  logo: images/favicon.png
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.tabs.link

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - cell_row_span
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - glightbox
  - search:
      lang:
        - en
extra_css:
#  - stylesheets/extra.css
  - stylesheets/style.css
extra:
  generator: false
